### ISSUE TITLE
Share the ACE preprocessing code

### ISSUE THREAD

**Issue by longlongman** [wasiahmad/GATE#1]
As far as I know, model performance on the ACE dataset is really sensitive to how you preprocess the data. I notice that you refer to the paper _Cross-lingual Structure Transfer for Relation and Event Extraction_ for preprocessing details, but they didn't share their code. I wonder whether you would like to share the preprocessing code.

**Comment by wasiahmad** [comment]
We do not have the preprocessing code too. Since we have the license for the ACE dataset, we requested the authors of that paper to share the preprocessed data which we used in our work.
