### ISSUE TITLE
excuse me

### ISSUE THREAD

**Issue by qlzw0530** [wasiahmad/GATE#10]
How are negative examples of data generated during the training phase

**Comment by wasiahmad** [comment]
For relation extraction task:

- Positive examples are composed of named entity pairs having a relationship
- Negative examples are composed of named entity pairs having "None"

For event argument role labeling task:

- Positive examples are composed of event trigger and one of its arguments (named entity) w/ role label
- Negative examples are composed of event trigger and named entities mentioned in the same sentence but the named entities do not play a role in the event (w/ role label "None")

We downsample the negative training instances by limiting the number of negative samples to be no more than the number of positive samples for each document.
