### ISSUE TITLE
What's the data in vocab.txt and how can I get it?

### ISSUE THREAD

**Issue by Aybss3535** [wasiahmad/GATE#11]
The ACE2005 dataset is prepared and I preprocessed it just as you describe. But when I run the script in /data/setup.sh, there is an error bacause I don't have the file 'vocab.txt'. Can you tell me what is the data in it and how can I get it?

**Comment by wasiahmad** [comment]
This part (https://github.com/wasiahmad/GATE/blob/main/data/setup.sh#L42) of the `setup.sh` script needs to be executed. Please check https://github.com/wasiahmad/GATE/blob/main/data/get_stat.py#L127.
