### ISSUE TITLE
parameters

### ISSUE THREAD

**Issue by qlzw0530** [wasiahmad/GATE#12]
Hello, I saw a lot of experimental data in the appendix of the paper on GATE. I would like to know whether these experiments were carried out
Uniform parameter Settings, for example:
--struct_position True \
--position_dim 30 \
--max_relative_pos 64  \
What do you remember about these Settings? I want to run your results according to your parameters?
Could you please tell me the parameters

**Comment by wasiahmad** [comment]
Yes, `position_dim` and `max_relative_pos` are fixed to those numbers. `struct_position` is for a particular baseline.

**Comment by qlzw0530** [comment]
What did you set position_DIM and max_relative_pos to?

**Comment by wasiahmad** [comment]
As you mentioned above, 30 and 64, respectively.

**Comment by qlzw0530** [comment]
prune keeping one？

**Comment by wasiahmad** [comment]
Yes, we kept pruning.
