### ISSUE TITLE
A query about your paper

### ISSUE THREAD

**Issue by Aybss3535** [wasiahmad/GATE#13]
I have two question struggle me for a long time, can you give me an answer? Thank you a lot.
Q1：You say "a k-layers GCN aggregates information of words that are k hop away. Such a way of embedding structure may hinder
cross-lingual transfer when the source and target languages have different path length distributions among words". Is the path distance refer to the distance in the syntactic structure? But the Gate and GCN both use the syntactic structure, what's the different?
Q2：You say "GCNs struggle to model words with long-range dependencies", is it beacuse it only aggregates information of words that are k hop away? But the Gate also attend the distance within delta, what's the different?

**Comment by wasiahmad** [comment]
1. Yes, path distance refers to the distance in the syntactic structure. Please read the paper carefully to understand the difference between GCN and GATE.
2. We can set an arbitrary value to `delta`.  A 1-layer GATE model can model dependencies between words that are k-hop away by setting `delta=k`. But for GCN, we need a k-layer GCN encoder.
