### ISSUE TITLE
POS-feature is useful？？？

### ISSUE THREAD

**Issue by qlzw0530** [wasiahmad/GATE#14]
Hello, may I ask whether you are using the POS feature? Because I find that the overall performance will decline after using the POS feature 。

use pos：59.03 | 62.35 | 59.70 | 70.09 | 54.3 | 57.4
not use：63.90| 68.8 | 59.4 | 68.8 | 55.14 | 59.00

**Comment by wasiahmad** [comment]
Yes, we used the POS feature. See our paper for details.

**Comment by qlzw0530** [comment]
in  1 1 2 2 as distance
use pos:：     59.0 | 62.3 | 59.7 | 70.0 | 54.3 | 57.4
your paper:    63.2| 68.5 | 58.7 | 69.5 | 52.7 | 53.7
I can't imagine why this would happen

**Comment by wasiahmad** [comment]
The difference is indeed large, but I am not sure why you are getting lower numbers. I suggest you try running experiments with different seeds and take the average.
