### ISSUE TITLE
vocab.txt

### ISSUE THREAD

**Issue by qlzw0530** [wasiahmad/GATE#16]
Hello, can you share your vocab. TXT file? In the VOCab. TXT file generated by me, the sorting of features is different, so the experimental performance cannot be consistent with yours

**Comment by wasiahmad** [comment]
It is not possible for us to retrieve our version of the vocab file. However, since we do not train word embeddings or multilingual BERT embeddings, it is fine if you construct your own version of the vocab file. The results should be close!
