### ISSUE TITLE
What is negative samples?

### ISSUE THREAD

**Issue by DevoAllen** [wasiahmad/GATE#5]
In the paper(Subburathinam et al. 2019) you followed for data preprocessing, they said _"We downsample the negative training instances by limiting the number of negative samples to be no more than the number of positive samples for each document"_. So what's the meaning of negative samples for argument role labeling, and how did you deal with this?

**Comment by wasiahmad** [comment]
In the EARL task, negative samples refer to instances where an entity does not play a role in an event. In such a case, the EARL model requires to predict `no_relation` for the negative `<event trigger, entity>` pairs.
