### ISSUE TITLE
Confusion over Dataset Processing

### ISSUE THREAD

**Issue by chensming** [wasiahmad/GATE#7]
Excuse me, I would like to ask you a question. I am very interested in your paper and want to do an experiment. But I don't quite understand the data processing part. Which directory should ACE2005 dataset be placed in? And what format is it needed to handle? Thank you very much for your answering.

**Comment by wasiahmad** [comment]
Hi, we did not provide any pre-processing script to prepare the ACE 2005 dataset, but we outlined the pre-processing steps in the paper. You can find the format of the preprocessed data in #2.

**Comment by chensming** [comment]
ok, thank you. I will read this part carefully. Looking forward to another excellent article from you. Good luck!
