### ISSUE TITLE
A query in the paper

### ISSUE THREAD

**Issue by chensming** [wasiahmad/GATE#8]
Hello, when I read the paper in Task Description(part 2), I notice the word "zero-short", do you mean zero-shot learning? 
![1634351154(1)](https://user-images.githubusercontent.com/45591767/137570015-3d564502-d269-42f8-8dd6-ff0f97fd9d10.png)

**Comment by wasiahmad** [comment]
Yes, sorry for the typo.

**Comment by chensming** [comment]
> Yes, sorry for the typo.

oh thanks. And I wonder how you get the language-universal tree structure using an off-the-shelf universal dependency parser. I would appreciate it if you could tell me the details. Did you refer to a github? Or did you use their api (could you give me the url of the introduce web pape? I'm not sure whether it's https://ufal.mff.cuni.cz/udpipe or https://github.com/ufal/udpipe? And which the version of the model did you adopt?). 

![image](https://user-images.githubusercontent.com/45591767/138376827-07df4455-43bf-44ad-b77a-35224de97749.png)

**Comment by wasiahmad** [comment]
It's the UDPIPE (python version). You may check this out: https://github.com/wasiahmad/Syntax-MBERT/tree/main/udpipe

**Comment by chensming** [comment]
> It's the UDPIPE (python version). You may check this out: https://github.com/wasiahmad/Syntax-MBERT/tree/main/udpipe

Thanks very much!
