### ISSUE TITLE
Something puzzling on experiments

### ISSUE THREAD

**Issue by chensming** [wasiahmad/GATE#9]
Hi, when talking about the experiments on sensitivity towards source language, I notice that you translate English test set into Chinese using Google Cloud Api, and I'm wonder whether you still need to label this translated Chinese example manually or by script(did you give the code?)

Moreover, I notice your another paper [Syntax-augmented Multilingual BERT for Cross-lingual Transfer](https://aclanthology.org/2021.acl-long.350.pdf), I want to know if Syntax-augmented MBERT can be used for relation extraction and event extraction tasks in this paper. Have you tested it, and if so, how effective is it?😇

Thanks for your answering.

**Comment by wasiahmad** [comment]
## Translation

No, you do not need to do any labeling. Let's say we have the following test example on **Event Argument Role Labeling** in Chinese.

```
"id": "CBS20001021.1000.0347-EV1-1CBS20001021.1000.0347-E14-36", 
"relation": "Victim", 
"subj_type": "Life-Die", 
"obj_type": "PER", 
"token": ["\u8d8a\u5357", "\u6e44\u516c", "\u6cb3", "\u5730\u533a", "\u6700\u8fd1", "\u56e0", "\u4e3a", "\u8fde", "\u7eed\u8c6a", "\u96e8\u9020", "\u6210", "\u4e86", "300\u591a", "\u4eba", "\u6b7b\u4ea1", "\uff0c"], 
"subj_start": 14, 
"subj_end": 14, 
"obj_start": 13, 
"obj_end": 13
```

We perform the translation as follows.

#### Chinese input

<img width="639" alt="Screen Shot 2020-03-27 at 1 16 41 PM" src="https://user-images.githubusercontent.com/17520413/77787266-4283e200-702d-11ea-876e-5a481b216ca5.png">

#### English translation

<img width="644" alt="Screen Shot 2020-03-27 at 1 16 48 PM" src="https://user-images.githubusercontent.com/17520413/77787291-4fa0d100-702d-11ea-8d78-197b28bdd244.png">

Here, `[<sub>, </sub>]` and `[<obj>, </obj>]` represents event trigger and one of its arguments.

----

## Evaluating Syntax-MBERT on IE tasks

We didn't evaluate Syntax-MBERT on the information extraction tasks, but presumably, it should boost the performance.

**Comment by chensming** [comment]
Thanks, bro.❤️
